name: Automated PR Review

on:
  pull_request:
    types: [opened, synchronize]

# Add explicit permissions for pull requests
permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Setup ES Module environment
        run: |
          mkdir -p .github/scripts
          echo '{"type":"module"}' > .github/scripts/package.json
          
      - name: Install dependencies
        run: npm install @octokit/rest

      - name: Run PR review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          node .github/scripts/review-pr.js
